version: "3.8"
services:
  master_jenkins:
    image: jenkins/jenkins:lts
    container_name: "master_jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ../Master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
